### ISSUE TITLE
SLS command not found

### ISSUE THREAD

**Issue by aligg73** [serverless-community-labs/serverless-plugin-simulate#71]
Hi,

I have installed the plugin, Docker I already had.
Serverless.yml is in place as well.

When I try to run the command I get:
sls simulate apigateway start -p 5000

No command 'sls' found, but there are 22 similar ones
sls: command not found

I am running Ubuntu 17.04.

Thanks for your help,
Alex

**Comment by gertjvr** [comment]
Hi Alex

Can you fill in the issue template will help us replicate / debug the issue.

**Comment by aligg73** [comment]
Thanks I have found the issue, I needed to install serverless globally first. Would help if that's included in the tutorial.

Best,
Alex

**Comment by gertjvr** [comment]
Installing serverless globally will work but will become an issue when your upgrading to a new version for a different project. I prefer installing it locally and using npm scripts to execute sls

package.json has a scripts sections
```
"scripts": {
   "sls": "sls"
}
```

`npm run sls -- command args`

if your using yarn then your can simply run

`yarn run sls -- command args`
