### ISSUE TITLE
Updating docker-lambda

### ISSUE THREAD

**Issue by nielslanting** [serverless-community-labs/serverless-plugin-simulate#73]
# This is a Feature Proposal

## Description
As of Mar 22, 2017 you can run Node.js v6.10 on Lambda. The current docker-lambda in the package.json is set to 0.9.1, the current version of docker-lambda is 0.13.1.

Can we update, so we can run Node.js v6.10.

**Comment by johncmckim** [comment]
I haven't released a new version for this yet, will look at doing that soon.
